### ISSUE TITLE
Liquid syntax error (line 112): Unknown tag 'gist' (Liquid::SyntaxError)😫

### ISSUE THREAD

**Issue by it-eyes** [jekyll/jekyll-gist#94]
when I change my jekyll version to "~> 4.2.1",my jekyll project reports the error on console.

```
D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/document.rb:23:in `unknown_tag': Liquid syntax error (line 112): Unknown tag 'gist' (Liquid::SyntaxError)
        from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/document.rb:11:in `block in parse'
        from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:32:in `parse'
        from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/document.rb:10:in `parse'
        from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/document.rb:5:in `parse'
        from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:132:in `parse'
```

I find the jekyll version is 4.2.2 , and the gist version is 1.5.0 
who can give me some advice to fix ths issues? thx

**Comment by ashmaroli** [comment]
On what version of Jekyll did the plugin work properly for you?

**Comment by it-eyes** [comment]
> On what version of Jekyll did the plugin work properly for you?

the version of jekyll is 4.2.2
